const kanjiData = {
        "日": { hán: "NHẬT", nghĩa: "Ngày, mặt trời", on: "ニチ, ジツ", kun: "ひ, -び", vidu: ["日本 (Nhật Bản)", "日曜日 (Chủ nhật)", "毎日 (Mỗi ngày)"] },
        "月": { hán: "NGUYỆT", nghĩa: "Trăng, tháng", on: "ゲツ, ガツ", kun: "つき", vidu: ["一月 (Tháng 1)", "月曜日 (Thứ hai)", "今月 (Tháng này)"] },
        "火": { hán: "HỎA", nghĩa: "Lửa", on: "カ", kun: "ひ", vidu: ["火曜日 (Thứ ba)", "火山 (Núi lửa)"] },
        "水": { hán: "THỦY", nghĩa: "Nước", on: "スイ", kun: "みず", vidu: ["水曜日 (Thứ tư)", "水道 (Nước máy)"] },
        "木": { hán: "MỘC", nghĩa: "Cây", on: "モク", kun: "ki", vidu: ["木曜日 (Thứ năm)", "大木 (Cây lớn)"] },
        "金": { hán: "KIM", nghĩa: "Vàng, tiền", on: "キン", kun: "かね", vidu: ["お金 (Tiền)", "金曜日 (Thứ sáu)"] },
        "土": { hán: "THỔ", nghĩa: "Đất", on: "ド, ト", kun: "つchi", vidu: ["土曜日 (Thứ bảy)", "土地 (Đất đai)"] },
        "車": { hán: "XA", nghĩa: "Xe", on: "シャ", kun: "くるま", vidu: ["電車 (Tàu điện)", "自動車 (Ô tô)"] },
        "門": { hán: "MÔN", nghĩa: "Cổng", on: "モン", kun: "かado", vidu: ["専門 (Chuyên môn)", "校門 (Cổng trường)"] },
        "田": { hán: "ĐIỀN", nghĩa: "Ruộng", on: "デン", kun: "た", vidu: ["水田 (Ruộng lúa nước)", "成田 (Sân bay Narita)"] },
        "山": { hán: "SƠN", nghĩa: "Núi", on: "サン", kun: "やま", vidu: ["富士山 (Núi Phú Sĩ)", "山道 (Đường núi)"] },
        "川": { hán: "XUYÊN", nghĩa: "Sông", on: "セン", kun: "かわ", vidu: ["小川 (Suối nhỏ)", "ナイル川 (Sông Nile)"] },
        "雨": { hán: "VŨ", nghĩa: "Mưa", on: "ウ", kun: "あめ", vidu: ["大雨 (Mưa lớn)", "雨天 (Trời mưa)"] },
        "天": { hán: "THIÊN", nghĩa: "Trời", on: "テン", kun: "あま", vidu: ["天気 (Thời tiết)", "天国 (Thiên đường)"] },
        "気": { hán: "KHÍ", nghĩa: "Khí, tinh thần", on: "キ", kun: "X", vidu: ["元気 (Khỏe mạnh)", "病気 (Bệnh)"] },
        "父": { hán: "PHỤ", nghĩa: "Bố", on: "フ", kun: "ちち", vidu: ["お父さん (Bố người khác)", "祖父 (Ông)"] },
        "母": { hán: "MẪU", nghĩa: "Mẹ", on: "ボ", kun: "はは", vidu: ["お母さん (Mẹ người khác)", "祖母 (Bà)"] },
        "私": { hán: "TƯ", nghĩa: "Tôi", on: "シ", kun: "わたし", vidu: ["私立大学 (Đại học tư lập)"] },
        "兄": { hán: "HUYNH", nghĩa: "Anh trai", on: "キョウ", kun: "あに", vidu: ["お兄さん (Anh trai người khác)"] },
        "姉": { hán: "TỶ", nghĩa: "Chị gái", on: "シ", kun: "あne", vidu: ["お姉さん (Chị gái người khác)"] },
        "弟": { hán: "ĐỆ", nghĩa: "Em trai", on: "ダイ", kun: "おとうto", vidu: ["兄弟 (Anh em)"] },
        "妹": { hán: "MUỘI", nghĩa: "Em gái", on: "マイ", kun: "いもうと", vidu: ["姉妹 (Chị em gái)"] },
        "一": { hán: "NHẤT", nghĩa: "1", on: "イチ", kun: "ひと", vidu: ["一月 (Tháng 1)", "一人 (1 người)"] },
        "二": { hán: "NHỊ", nghĩa: "2", on: "ニ", kun: "ふた", vidu: ["二月 (Tháng 2)", "二日 (Ngày 2)"] },
        "三": { hán: "TAM", nghĩa: "3", on: "サン", kun: "みっ", vidu: ["三月 (Tháng 3)", "三日 (Ngày 3)"] },
        "四": { hán: "TỨ", nghĩa: "4", on: "シ", kun: "よん", vidu: ["四月 (Tháng 4)", "四日 (Ngày 4)"] },
        "五": { hán: "NGŨ", nghĩa: "5", on: "ゴ", kun: "いつ", vidu: ["五月 (Tháng 5)", "五日 (Ngày 5)"] },
        "六": { hán: "LỤC", nghĩa: "6", on: "ロク", kun: "むっ", vidu: ["六月 (Tháng 6)", "六日 (Ngày 6)"] },
        "七": { hán: "THẤT", nghĩa: "7", on: "シチ", kun: "なな", vidu: ["七月 (Tháng 7)", "七日 (Ngày 7)"] },
        "八": { hán: "BÁT", nghĩa: "8", on: "ハチ", kun: "やっ", vidu: ["八月 (Tháng 8)", "八日 (Ngày 8)"] },
        "九": { hán: "CỬU", nghĩa: "9", on: "キュウ, ク", kun: "ここの", vidu: ["九月 (Tháng 9)", "九日 (Ngày 9)"] },
        "十": { hán: "THẬP", nghĩa: "10", on: "ジュウ", kun: "とお", vidu: ["十月 (Tháng 10)", "十日 (Ngày 10)"] },
        "百": { hán: "BÁCH", nghĩa: "100", on: "ヒャク", kun: "X", vidu: ["三百 (300)", "六百 (600)"] },
        "千": { hán: "THIÊN", nghĩa: "1000", on: "セン", kun: "ち", vidu: ["三千 (3000)", "千葉 (Chiba)"] },
        "万": { hán: "VẠN", nghĩa: "10000", on: "マン, バン", kun: "X", vidu: ["一万円 (1 vạn yên)"] },
        "円": { hán: "YÊN", nghĩa: "Tiền Yên, Tròn", on: "エン", kun: "まる", vidu: ["円い (Tròn)", "一万円 (1 vạn yên)"] },
        "年": { hán: "NIÊN", nghĩa: "Năm", on: "ネン", kun: "とし", vidu: ["今年 (Năm nay)", "来年 (Sang năm)"] },
        "半": { hán: "BÁN", nghĩa: "Một nửa", on: "ハン", kun: "なか", vidu: ["三時半 (3 giờ rưỡi)"] },
        "分": { hán: "PHÂN", nghĩa: "Phút, chia", on: "フン, ブン", kun: "わか", vidu: ["十分 (10 phút)", "分かる (Hiểu)"] },
        "時": { hán: "THỜI", nghĩa: "Giờ", on: "ジ", kun: "とき", vidu: ["時間 (Thời gian)", "時計 (Đồng hồ)"] },
        "人": { hán: "NHÂN", nghĩa: "Người", on: "ジン, ニン", kun: "ひと", vidu: ["日本人 (Người Nhật)", "三人 (3 người)"] },
        "女": { hán: "NỮ", nghĩa: "Phụ nữ", on: "ジョ", kun: "おんな", vidu: ["女の子 (Bé gái)", "彼女 (Cô ấy)"] },
        "男": { hán: "NAM", nghĩa: "Đàn ông", on: "ダン, ナン", kun: "おとこ", vidu: ["男の子 (Bé trai)"] },
        "生": { hán: "SINH", nghĩa: "Sống, sinh ra", on: "セイ", kun: "い-きる", vidu: ["学生 (Học sinh)", "先生 (Giáo viên)"] },
        "子": { hán: "TỬ", nghĩa: "Con", on: "シ", kun: "こ", vidu: ["子供 (Trẻ em)", "椅子 (Cái ghế)"] },
        "学": { hán: "HỌC", nghĩa: "Học", on: "ガク", kun: "まな-ぶ", vidu: ["学校 (Trường học)", "大学 (Đại học)"] },
        "先": { hán: "TIÊN", nghĩa: "Trước", on: "セン", kun: "さき", vidu: ["先生 (Thầy cô)", "先月 (Tháng trước)"] },
        "白": { hán: "BẠCH", nghĩa: "Trắng", on: "ハク", kun: "しろ", vidu: ["白い (Trắng)", "白人 (Người da trắng)"] },
        "口": { hán: "KHẨU", nghĩa: "Miệng", on: "コウ", kun: "くち", vidu: ["入口 (Lối vào)", "人口 (Dân số)"] },
        "石": { hán: "THẠCH", nghĩa: "Đá", on: "セキ", kun: "いし", vidu: ["石 (Hòn đá)", "石油 (Dầu mỏ)"] },
        "手": { hán: "THỦ", nghĩa: "Tay", on: "シュ", kun: "て", vidu: ["上手 (Giỏi)", "手紙 (Lá thư)"] },
        "足": { hán: "TÚC", nghĩa: "Chân", on: "ソク", kun: "あし", vidu: ["足りる (Đủ)", "遠足 (Dã ngoại)"] },
        "耳": { hán: "NHĨ", nghĩa: "Tai", on: "ジ", kun: "みみ", vidu: ["耳 (Cái tai)"] },
        "目": { hán: "MỤC", nghĩa: "Mắt", on: "モク", kun: "め", vidu: ["目次 (Mục lục)", "目的 (Mục đích)"] },
        "体": { hán: "THỂ", nghĩa: "Cơ thể", on: "タイ", kun: "からだ", vidu: ["体力 (Thể lực)", "体育 (Thể dục)"] },
        "上": { hán: "THƯỢNG", nghĩa: "Trên", on: "ジョウ", kun: "うえ", vidu: ["屋上 (Sân thượng)", "上がる (Lên)"] },
        "下": { hán: "HẠ", nghĩa: "Dưới", on: "カ, ゲ", kun: "した", vidu: ["地下鉄 (Tàu điện ngầm)", "下がる (Xuống)"] },
        "中": { hán: "TRUNG", nghĩa: "Trong, giữa", on: "チュウ", kun: "なか", vidu: ["中国 (Trung Quốc)", "中心 (Trung tâm)"] },
        "大": { hán: "ĐẠI", nghĩa: "Lớn", on: "ダイ", kun: "おお-ki", vidu: ["大学 (Đại học)", "大会 (Đại hội)"] },
        "小": { hán: "TIỂU", nghĩa: "Nhỏ", on: "ショウ", kun: "ちい-さい", vidu: ["小学校 (Trường tiểu học)"] },
        "本": { hán: "BẢN", nghĩa: "Sách, gốc", on: "ホン", kun: "もと", vidu: ["日本語 (Tiếng Nhật)", "本日 (Hôm nay)"] },
        "力": { hán: "LỰC", nghĩa: "Sức mạnh", on: "リョク", kun: "ちから", vidu: ["能力 (Năng lực)", "火力 (Hỏa lực)"] },
        "何": { hán: "HÀ", nghĩa: "Cái gì", on: "カ", kun: "なに, なん", vidu: ["何時 (Mấy giờ)", "何か (Cái gì đó)"] },
        "出": { hán: "XUẤT", nghĩa: "Ra ngoài", on: "シュツ", kun: "で-る", vidu: ["出口 (Lối ra)", "出発 (Xuất phát)"] },
        "入": { hán: "NHẬP", nghĩa: "Vào trong", on: "ニュウ", kun: "はい-る", vidu: ["入口 (Lối vào)", "入学 (Nhập học)"] },
        "明": { hán: "MINH", nghĩa: "Sáng", on: "メイ", kun: "あか-るい", vidu: ["明日 (Ngày mai)", "説明 (Giải thích)"] },
        "休": { hán: "HƯU", nghĩa: "Nghỉ ngơi", on: "キュウ", kun: "やす-む", vidu: ["休み (Nghỉ phép)", "休日 (Ngày nghỉ)"] },
        "好": { hán: "HẢO", nghĩa: "Thích", on: "コウ", kun: "す-ki", vidu: ["大好き (Rất thích)", "好意 (Thiện chí)"] },
        "間": { hán: "GIAN", nghĩa: "Giữa, khoảng", on: "カン", kun: "あいだ", vidu: ["時間 (Thời gian)", "間に合う (Kịp giờ)"] },
        "岩": { hán: "NHAM", nghĩa: "Đá núi", on: "ガン", kun: "いわ", vidu: ["岩石 (Nham thạch)"] },
        "畑": { hán: "ĐIỀN", nghĩa: "Cánh đồng", on: "X", kun: "はたけ", vidu: ["田畑 (Ruộng đồng)"] },
        "森": { hán: "SÂM", nghĩa: "Rừng rậm", on: "シン", kun: "もり", vidu: ["森林 (Rừng rậm)"] },
        "林": { hán: "LÂM", nghĩa: "Rừng thưa", on: "リン", kun: "はやし", vidu: ["林道 (Đường rừng)"] },
        "右": { hán: "HỮU", nghĩa: "Bên phải", on: "ウ, ユウ", kun: "みぎ", vidu: ["右手 (Tay phải)", "右折 (Rẽ phải)"] },
        "左": { hán: "TẢ", nghĩa: "Bên trái", on: "サ", kun: "ひだり", vidu: ["左手 (Tay trái)", "左折 (Rẽ trái)"] },
        "東": { hán: "ĐÔNG", nghĩa: "Phía Đông", on: "トウ", kun: "ひ가し", vidu: ["東京 (Tokyo)", "中東 (Trung Đông)"] },
        "西": { hán: "TÂY", nghĩa: "Phía Tây", on: "セイ, サイ", kun: "にし", vidu: ["関西 (Kansai)", "西洋 (Tây Âu)"] },
        "北": { hán: "BẮC", nghĩa: "Phía Bắc", on: "ホク", kun: "きた", vidu: ["北海道 (Hokkaido)", "南北 (Nam Bắc)"] },
        "南": { hán: "NAM", nghĩa: "Phía Nam", on: "ナン", kun: "みなみ", vidu: ["東南アジア (Đông Nam Á)"] },
        "外": { hán: "NGOẠI", nghĩa: "Ngoài", on: "ガイ", kun: "そと", vidu: ["外国人 (Người nước ngoài)", "外出 (Ra ngoài)"] },
        "内": { hán: "NỘI", nghĩa: "Trong", on: "ナイ", kun: "うち", vidu: ["内容 (Nội dung)", "家内 (Vợ mình)"] },
        "駅": { hán: "DỊCH", nghĩa: "Nhà ga", on: "エキ", kun: "X", vidu: ["駅員 (Nhân viên ga)", "東京駅 (Ga Tokyo)"] },
        "会": { hán: "HỘI", nghĩa: "Gặp gỡ", on: "カイ", kun: "あ-う", vidu: ["会社 (Công ty)", "会議 (Hội nghị)"] },
        "長": { hán: "TRƯỜNG", nghĩa: "Dài, trưởng", on: "チョウ", kun: "なが-い", vidu: ["社長 (Giám đốc)", "校長 (Hiệu trưởng)"] },
        "高": { hán: "CAO", nghĩa: "Cao, đắt", on: "コウ", kun: "たか-い", vidu: ["高校 (Trường cấp 3)", "最高 (Tuyệt nhất)"] },
        "名": { hán: "DANH", nghĩa: "Tên", on: "メイ", kun: "な", vidu: ["名前 (Tên)", "有名 (Nổi tiếng)"] },
        "行": { hán: "HÀNH", nghĩa: "Đi", on: "コウ", kun: "い-ku", vidu: ["旅行 (Du lịch)", "銀行 (Ngân hàng)"] },
        "来": { hán: "LA", nghĩa: "Đến", on: "ライ", kun: "く-る", vidu: ["来年 (Sang năm)", "将来 (Tương lai)"] },
        "食": { hán: "THỰC", nghĩa: "Ăn", on: "ショク", kun: "た-べる", vidu: ["食べ物 (Đồ ăn)", "食堂 (Nhà ăn)"] },
        "見": { hán: "KIẾN", nghĩa: "Nhìn, xem", on: "ケン", kun: "み-る", vidu: ["見学 (Tham quan)", "意見 (Ý kiến)"] },
        "聞": { hán: "VĂN", nghĩa: "Nghe", on: "ブン", kun: "き-く", vidu: ["新聞 (Báo chí)", "聞き取り (Luyện nghe)"] },
        "読": { hán: "ĐỘC", nghĩa: "Đọc", on: "ドク", kun: "よ-む", vidu: ["読書 (Đọc sách)"] },
        "書": { hán: "THƯ", nghĩa: "Viết", on: "ショ", kun: "か-く", vidu: ["辞書 (Từ điển)", "教科書 (Sách giáo khoa)"] },
        "話": { hán: "THOẠI", nghĩa: "Nói chuyện", on: "ワ", kun: "はな-す", vidu: ["電話 (Điện thoại)", "会話 (Hội thoại)"] },
        "午": { hán: "NGỌ", nghĩa: "Chính ngọ", on: "ゴ", kun: "X", vidu: ["午前 (Sáng/AM)", "午後 (Chiều/PM)"] },
        "前": { hán: "TIỀN", nghĩa: "Trước", on: "ゼン", kun: "mae", vidu: ["名前 (Tên)", "三日前 (3 ngày trước)"] },
        "後": { hán: "HẬU", nghĩa: "Sau", on: "ゴ, コウ", kun: "ato, ushiro", vidu: ["最後 (Cuối cùng)", "後ろ (Phía sau)"] },
        "每": { hán: "MỖI", nghĩa: "Mọi, mỗi", on: "マイ", kun: "X", vidu: ["毎日 (Mỗi ngày)", "毎朝 (Mỗi sáng)"] },
        "校": { hán: "HIỆU", nghĩa: "Trường học", on: "コウ", kun: "X", vidu: ["学校 (Trường học)", "校長 (Hiệu trưởng)"] },
        "語": { hán: "NGỮ", nghĩa: "Ngôn ngữ", on: "ゴ", kun: "かた-る", vidu: ["日本語 (Tiếng Nhật)", "単語 (Từ vựng)"] },
        "今": { hán: "KIM", nghĩa: "Bây giờ", on: "コン", kun: "いま", vidu: ["今日 (Hôm nay)", "今月 (Tháng này)"] },
        "電": { hán: "ĐIỆN", nghĩa: "Điện", on: "デン", kun: "X", vidu: ["電車 (Tàu điện)", "電気 (Điện/Đèn)"] },
        "国": { hán: "QUỐC", nghĩa: "Đất nước", on: "コク", kun: "くに", vidu: ["外国人 (Người nước ngoài)", "中国 (Trung Quốc)"] }
    };